Add encryption and access control docs
spheronFdn/docs pull request #100
Opened 2023-09-22 12:26 UTC by aayushmahapatra

2023-09-28 14:15 UTC, rekpero requested changes

2023-09-28 14:15 UTC, rekpero commented on pages/storage/encryption.mdx
> +  - **token** - The upload token was fetched from the server.
there is no token in the example configuration

2023-09-29 14:59 UTC, aayushmahapatra commented on pages/storage/encryption.mdx
> +  - **token** - The upload token was fetched from the server.
Done.

2023-09-29 16:23 UTC, rekpero approved these changes

2023-09-29 16:23 UTC, merged