Add browser upload sdk vs storage sdk
spheronFdn/docs pull request #101
Opened 2023-09-22 13:03 UTC by aayushmahapatra

2023-09-28 14:24 UTC, rekpero requested changes
need some changes

2023-09-28 14:24 UTC, rekpero commented on pages/storage/comparision.mdx
> +| SDK Packages         | @spheron/browser-upload                          | @spheron/storage                                       |
put npm link here

2023-09-28 14:24 UTC, rekpero commented on pages/storage/comparision.mdx
> +| Token Expiry         | Token expires after one upload (10-minute limit) | No token required, operates on the server-side         |
why no token required? expiry can be set by user when generating the token

2023-09-29 11:32 UTC, rekpero requested changes

2023-09-29 11:32 UTC, rekpero commented on pages/storage/comparision.mdx
> +# Browser Upload SDK vs. Storage SDK
name the sidebar title - `SDK Comparision`

2023-09-29 14:59 UTC, aayushmahapatra commented on pages/storage/comparision.mdx
> +# Browser Upload SDK vs. Storage SDK
It's named - `Browser vs Storage` in #102

2023-10-02 17:31 UTC, rekpero approved these changes

2023-10-02 18:18 UTC, merged