Add rate limits section under Storage
spheronFdn/docs pull request #102
Opened 2023-09-23 04:12 UTC by aayushmahapatra

2023-10-02 19:19 UTC, rekpero requested changes
check my comments

2023-10-02 19:19 UTC, rekpero commented on pages/storage/rate-limits.mdx
> +| **CDN Bandwidth (GB)**           | 100         | 100      | 100     | 100       |
same with others

2023-10-02 19:19 UTC, rekpero commented on pages/storage/rate-limits.mdx
> +| **Optimized Images**             | 25          | 100      | 500     | 2000      |
remove these

2023-10-02 19:19 UTC, rekpero commented on pages/storage/rate-limits.mdx
> +| **IPFS Gateway Service Domains** | 9999        | 9999     | 9999    | 9999      |
change this title to `IPFS Gateway`- put infinity icon

2023-10-02 19:19 UTC, rekpero commented on pages/storage/rate-limits.mdx
> +|                                  | **Default** | **Lite** | **Pro** | **Wagmi** |
also wait where is the rate limit in here like how much file size can be uploaded

2023-10-03 05:44 UTC, aayushmahapatra commented on pages/storage/rate-limits.mdx
> +|                                  | **Default** | **Lite** | **Pro** | **Wagmi** |
It's mentioned like - `Storage IPFS`, `Storage Filecoin`

2023-10-05 06:16 UTC, rekpero requested changes
check my comments

2023-10-05 06:16 UTC, rekpero commented on pages/storage/rate-limits.mdx
> +| **CDN Bandwidth (GB)**    | 100 GB              | 100 GB           | 100 GB          | 100 GB            |
Also add emoji 💲 on - 
CDN Bandwidth, Storage Arweave, HNS, ENS

Also rename Storage Arweave to Arweave Storage, same with IPFS

2023-10-05 06:16 UTC, rekpero commented on pages/storage/rate-limits.mdx
> +| **Storage Filecoin (GB)** | 5 GB                | 40 GB            | 150 GB          | 800 GB            |
remove this

2023-10-05 06:16 UTC, rekpero commented on pages/storage/rate-limits.mdx
> +| **Storage Filecoin (GB)** | 5 GB                | 40 GB            | 150 GB          | 800 GB            |
Add this note at the end say - `By default, Filecoin storage utilizes IPFS storage. Therefore, storage consumption is capped at the IPFS storage limit. In simpler terms, you can upload until you reach the IPFS storage capacity.`

2023-10-05 06:20 UTC, rekpero commented on pages/storage/rate-limits.mdx
> +|                                  | **Default** | **Lite** | **Pro** | **Wagmi** |
I'm talking about `File upload size / Request` rate limit. What you have mostly mention is about the plan and all. But mention this as well. check with milos for this

2023-10-09 16:22 UTC, rekpero approved these changes

2023-10-09 17:23 UTC, merged