Add billing section under Storage
spheronFdn/docs pull request #103
Opened 2023-09-23 04:27 UTC by aayushmahapatra

2023-10-05 06:34 UTC, rekpero requested changes

2023-10-05 06:34 UTC, rekpero commented on pages/storage/billing.mdx
> +- **ENTERPRISE:** Seeking even greater possibilities? Envisioning a complex integration? Share detailed information about your company and project in the form below, and we will promptly respond to y
add the end of the para, just mention connect with the team for more details and add the contact link

2023-10-05 06:34 UTC, rekpero commented on pages/storage/billing.mdx
> +| SPHERON ENTERPRISE | IPFS         | Contact Sales   | Custom            | Custom        |
in contact sale, mention the link

2023-10-05 06:34 UTC, rekpero commented on pages/storage/billing.mdx
> +## Flexible Plan Upgrades
mention bonuses that users can add by themself and their pricing

2023-10-09 19:03 UTC, aayushmahapatra commented on pages/storage/billing.mdx
> +## Flexible Plan Upgrades
Done

2023-10-09 19:41 UTC, rekpero requested changes

2023-10-09 19:41 UTC, rekpero commented on pages/storage/billing.mdx
> +Explore our range of plans:
these are Ad-ons, not plan. Please mention it properly

2023-10-09 19:41 UTC, rekpero commented on pages/storage/billing.mdx
> +Explore our range of plans:
also mention the pricing for each

2023-10-10 17:22 UTC, rekpero requested changes

2023-10-10 17:22 UTC, rekpero commented on pages/storage/billing.mdx
> +| Image Optimization | $4 / 1000 images |
remove this

2023-10-10 17:22 UTC, rekpero commented on pages/storage/billing.mdx
> +| IPFS Storage       | $0.3 / 3 GB      |
remove this

2023-10-10 17:40 UTC, rekpero requested changes

2023-10-10 17:40 UTC, rekpero commented on pages/storage/billing.mdx
> +| Ens Domains      | $1 / domain  |
HNS and ENS

2023-10-10 19:16 UTC, rekpero requested changes

2023-10-10 19:16 UTC, rekpero commented on pages/storage/billing.mdx
> +| CDN Bandwidth    | $40 / 100 GB |
can you add gateway bandwidth? I just remembered it

2023-10-10 19:16 UTC, rekpero commented on pages/storage/billing.mdx
> +| CDN Bandwidth    | $40 / 100 GB |
it's $40/100GB

2023-10-10 19:45 UTC, aayushmahapatra commented on pages/storage/billing.mdx
> +| CDN Bandwidth    | $40 / 100 GB |
Can you tell me the price for it?

2023-10-10 23:58 UTC, rekpero approved these changes

2023-10-11 03:48 UTC, merged