Update billing section in docs
spheronFdn/docs pull request #107
Opened 2023-09-27 14:36 UTC by aayushmahapatra

2023-10-16 21:42 UTC, rekpero requested changes
check my comments

2023-10-16 21:42 UTC, rekpero commented on pages/billing/upgrade/credit-card.mdx
> +   - If you have a coupon code, you can add it in the **Coupon code** section and Click on the arrow button to activate it.
remove the coupon code section from everywhere. we don't have coupon code on our plan upgrade page

2023-10-16 21:42 UTC, rekpero commented on pages/billing/upgrade/credit-card.mdx
> +   - If you have a coupon code, you can add it in the **Coupon code** section and Click on the arrow button to activate it.
do it from other places as well

2023-10-16 21:42 UTC, rekpero commented on pages/billing/upgrade/credit-card.mdx
> +   - If you have a coupon code, you can add it in the **Coupon code** section and Click on the arrow button to activate it.
Also create another PR for applying credit on org

2023-10-17 11:04 UTC, aayushmahapatra commented on pages/billing/upgrade/credit-card.mdx
> +   - If you have a coupon code, you can add it in the **Coupon code** section and Click on the arrow button to activate it.
Didn't get what you mean by this?

2023-10-17 16:42 UTC, rekpero commented on pages/billing/upgrade/credit-card.mdx
> +   - If you have a coupon code, you can add it in the **Coupon code** section and Click on the arrow button to activate it.
bro check the app now. when you are in the plan upgrade section now there is no coupon section to add any type of coupon. we have remove the coupon logic with a credit based system. didn't you know about this feature yet?

2023-10-17 17:10 UTC, aayushmahapatra commented on pages/billing/upgrade/credit-card.mdx
> +   - If you have a coupon code, you can add it in the **Coupon code** section and Click on the arrow button to activate it.
Oh! You wrote credit so got confused cause on the platform it's Coupon Credit.

2023-10-18 05:08 UTC, merged