Add docs for coupon credits
spheronFdn/docs pull request #114
Opened 2023-10-18 13:39 UTC by aayushmahapatra

2023-10-23 18:42 UTC, rekpero requested changes

2023-10-23 18:42 UTC, rekpero commented on pages/billing/credits.mdx
> +You can use coupon credits to add bonuses for free.
not for free bro, it'll deduct from credit

2023-10-25 05:15 UTC, rekpero requested changes

2023-10-25 05:15 UTC, rekpero commented on pages/billing/credits.mdx
> +4. You can view the status of all your credits here, categorized as Active, Pending, and Expired.
mention how to use these credits as well. like add upgrade plan with credits, add ad-ons with credits and topup compute credit with credits

2023-10-25 05:15 UTC, rekpero commented on pages/billing/credits.mdx
> +4. You can view the status of all your credits here, categorized as Active, Pending, and Expired.
add these section and then we are good

2023-10-25 15:53 UTC, rekpero requested changes
bro don't you read the content you are copying and also are you not trying it yourself, why is the whole context messed up? You should try the feature before you should write the steps around it, a lot of improvement has been done from last time the steps are now not the same, you should check properly what we should write instead of copying it blindly

2023-10-25 15:53 UTC, rekpero commented on pages/billing/credits.mdx
> +7. Add the amount you want to deposit and Click "Deposit." Make sure it is not more than the approved amount, or else the transaction will fail.
why is this step needed for credit payment? did you not tried it yourself??? Credit shouldn't need user to deposit any token to escrow wallet

2023-10-25 15:53 UTC, rekpero commented on pages/billing/credits.mdx
> +6. Read the transaction details, and Click "Add" to initiate the transaction.
```suggestion
6. Read the add-on's payment details, and Click "Add" to initiate the payment.
```

2023-10-25 15:53 UTC, rekpero commented on pages/billing/credits.mdx
> +3. To add more add-on fields, Click "Add Add-on Field".
Remove this as this is not possible. there is no other add-on fields on the compute anyways

2023-10-25 15:53 UTC, rekpero commented on pages/billing/credits.mdx
> +2. Click "Top Up" under **Balance** and Select `Compute Credits` in Add-on and the Amount you wish to add.
```suggestion
2. Click "Top Up" under **Balance** and Select `Compute Credits` in Add-on and the Amount you wish to add and click on Review.
```

2023-10-25 15:53 UTC, rekpero commented on pages/billing/credits.mdx
> +4. After adding all the add-on fields, Click "Review."
remove this step

2023-10-25 15:53 UTC, rekpero commented on pages/billing/credits.mdx
> +6. Read the transaction details, and Click "Add" to initiate the transaction.
```suggestion
6. Read the add-on's payment details, and Click "Add" to initiate the payment.
```

2023-10-25 15:53 UTC, rekpero commented on pages/billing/credits.mdx
> +7. Upon successful transaction, the Add-on will be added.
```suggestion
7. Upon successful payment, the Add-on will be added.
```

2023-10-25 15:53 UTC, rekpero commented on pages/billing/credits.mdx
> +7. Upon successful transaction, the Add-on will be added.
```suggestion
7. Upon successful payment, the Add-on will be added.
```

2023-10-25 15:53 UTC, rekpero commented on pages/billing/credits.mdx
> +8. Click "Upgrade Plan" to initiate the transaction. Upon successful transaction, the plan will be upgraded to Pro.
```suggestion
8. Click "Upgrade Plan" to initiate the payment. Upon successful deduction from credit, the plan will be upgraded to Pro.
```

2023-10-25 16:36 UTC, aayushmahapatra commented on pages/billing/credits.mdx
> +3. To add more add-on fields, Click "Add Add-on Field".
We should remove the `Add Add-on Field` button also.

2023-10-25 17:26 UTC, rekpero requested changes

2023-10-25 17:26 UTC, rekpero commented on pages/billing/credits.mdx
> +4. Read the transaction details and Click "Upgrade Plan" to initiate the payment. Upon successful deduction from credit, the plan will be upgraded to Pro.
```suggestion
4. Read the payment details and Click "Upgrade Plan" to initiate the payment. Upon successful deduction from credit, the plan will be upgraded to Pro.
```

2023-10-25 17:45 UTC, rekpero approved these changes

2023-10-25 17:46 UTC, merged