add copy functionality
spheronFdn/docs pull request #118
Opened 2023-10-25 19:08 UTC by Giri-Spheron

Updated to nextra's new version with copy option in code snippet

2023-10-25 20:26 UTC, aayushmahapatra requested changes
Some changes required. Also, make sure to format the code before pushing.

2023-10-25 20:26 UTC, aayushmahapatra commented on next.config.js
> +const withNextra = require("nextra")(
```suggestion
const withNextra = require("nextra")({
```

2023-10-25 20:26 UTC, aayushmahapatra commented on next.config.js
> +  {
Remove this.

2023-10-26 16:58 UTC, Giri-Spheron commented on next.config.js
> +  {
done changes

2023-10-26 17:35 UTC, aayushmahapatra approved these changes

2023-10-26 17:35 UTC, merged