Add GPU docs [WIP]
spheronFdn/docs pull request #126
Opened 2023-11-07 16:55 UTC by aayushmahapatra

2023-11-10 05:42 UTC, rekpero requested changes

2023-11-10 05:42 UTC, rekpero commented on components/plans.tsx
> +    amount: "548.25",
fix the pricing. check the current price

2023-11-10 05:42 UTC, rekpero commented on components/plans.tsx
> +    amount: "548.25",
check other plans as well

2023-11-10 09:31 UTC, aayushmahapatra commented on components/plans.tsx
> +    amount: "548.25",
Done. A100 is the same. Updated the others.

2023-11-10 09:32 UTC, rekpero requested changes

2023-11-10 09:32 UTC, rekpero commented on components/plans.tsx
> +    dailyAmount: "10.18",
show hourly rate instead of daily

2023-11-10 10:22 UTC, rekpero requested changes

2023-11-10 10:22 UTC, rekpero commented on components/plans-card.tsx
> +          <p className={styles.dailyAmount}>${hourlyAmount} avg hourly cost</p>
make hourly primary for both gpu and CPU 
also convert the cpus to hourly rate

2023-11-10 10:22 UTC, rekpero requested changes

2023-11-10 10:22 UTC, rekpero commented on components/plans.tsx
> +  {
remove v100 from the list

2023-11-11 08:52 UTC, rekpero approved these changes

2023-11-11 09:21 UTC, merged