Add storage overview
spheronFdn/docs pull request #137
Opened 2023-12-19 04:33 UTC by aayushmahapatra

2023-12-20 02:42 UTC, rekpero requested changes
check my review comments

2023-12-20 02:42 UTC, rekpero commented on pages/storage.mdx
> +Spheron Storage streamlines decentralized storage with its user-friendly features, offering a pinning service that simplifies
Please mention other storage options, focusing on IPFS, but it's also vital to mention Filecoin and Arweave in different places. Otherwise, a user interested in using Filecoin or Arweave will misunderstand and move on. It's not intuitively understandable that multi-storage means IPFS, Filecoin & Arweave.

2023-12-20 02:42 UTC, rekpero commented on pages/storage.mdx
> +Spheron Storage streamlines decentralized storage with its user-friendly features, offering a pinning service that simplifies
Please update all the points based on this context

2023-12-20 02:42 UTC, rekpero commented on pages/storage.mdx
> +- **Cost-Effective Pricing:**
Cost Effective Pricing for IPFS

2023-12-20 02:42 UTC, rekpero commented on pages/storage.mdx
> +  Spheron Storage is your reliable solution for decentralized storage needs, offering a connected and straightforward experience. Whether you're uploading new assets or linking existing ones, trust S
WTF is this? mention why spheron is reliable, not just say blindly that trust us lol

2023-12-20 02:42 UTC, rekpero commented on components/storage.tsx
> +    title: "Upload",
```suggestion
    title: "Upload Files",
```

2023-12-20 02:42 UTC, rekpero commented on components/storage.tsx
> +    title: "Buckets",
Storage SDK

2023-12-20 02:42 UTC, rekpero commented on components/storage.tsx
> +    title: "Encryption",
IPNS SDK

2023-12-20 02:42 UTC, rekpero commented on components/storage.tsx
> +    title: "Billing",
Encryption

2023-12-21 09:39 UTC, aayushmahapatra commented on components/storage.tsx
> +    title: "Encryption",
Done.

2023-12-21 15:27 UTC, rekpero requested changes

2023-12-21 15:27 UTC, rekpero commented on components/storage.tsx
> +    title: "Storage SDK V2",
no need to mention V2 here, the transition is already done

2023-12-21 15:27 UTC, rekpero commented on pages/storage.mdx
> +  With Spheron Storage, you can count on reliable uptime for your assets. Our robust infrastructure and advanced monitoring systems minimize downtime, ensuring a seamless experience for your users.
Mention at the end - Checkout our [Statuspage](https://status.spheron.network) to gain more visibility into IPFS nodes and upload pipeline's uptime.

2023-12-21 15:29 UTC, rekpero requested changes

2023-12-21 15:29 UTC, rekpero commented on pages/storage.mdx
> +
Mention in-built IPNS capability as well

2023-12-21 16:51 UTC, aayushmahapatra commented on pages/storage.mdx
> +  With Spheron Storage, you can count on reliable uptime for your assets. Our robust infrastructure and advanced monitoring systems minimize downtime, ensuring a seamless experience for your users.
Done.

2023-12-21 16:51 UTC, aayushmahapatra commented on pages/storage.mdx
> +
Done.

2023-12-21 17:34 UTC, rekpero approved these changes

2023-12-21 17:42 UTC, merged