Refactor docs and update for streamlined compute billing #142
spheronFdn/docs pull request #143
Opened 2024-01-08 11:53 UTC by anataliocs

2024-01-09 04:33 UTC, anataliocs commented on pnpm-lock.yaml
> +    dev: false
```suggestion
    dev: false
    
```

2024-01-09 11:35 UTC, rekpero requested changes
@anataliocs review done, check my RC

2024-01-09 11:35 UTC, rekpero commented on pages/billing/compute/compute-usage.mdx
> +
mention this -> when you go inside the cluster, you can even see full breakdown on each instance usage and monthly cost.

2024-01-09 11:35 UTC, rekpero commented on pages/billing/compute/topup-compute-funds.mdx
> +- Add a [Web3 Payment Method](/billing/payment-method/#connect-wallet) and deposit funds in your [Spheron escrow wallet](/billing/funds/)
instead of aggregating it like this, I think it would be better if you do 2 guide - 
1. Topup with your fav web3 wallet
2. Topup with your credit card

Then show the whole process of attaching the wallet, depositing and then paying for the topup. 

Reason -> A Lot of users think that depositing the token is the last step of the top-up and their instances are going down because they don't have any balance to pay for it.

2024-01-09 11:35 UTC, rekpero commented on pages/billing/storage/storage-plan.mdx
> +The Free Starter Plan is capped at 5GB of IPFS storage and 10GB of bandwidth.  Arweave is not available for Starter Plan users.
make this a note instead

2024-01-09 11:35 UTC, rekpero commented on pages/billing/storage/storage-plan.mdx
> +When you need more storage, bandwidth or access to Arweave you can upgrade your plan.
access to arweave doesn't particularly need any upgrade, user can buy arweave storage ad-on to access it

2024-01-09 11:35 UTC, rekpero commented on pages/billing/storage/storage-plan-details.mdx
> +| Parallel Uploads  | $12 / upload |
```suggestion
| Parallel Uploads  | $2 / upload |
```

2024-01-09 11:35 UTC, rekpero commented on pages/billing/funds.mdx
>  4. Add the amount you want to deposit and Click "Deposit."
we clubbed these 2 section, now approve and deposit tx are chained

2024-01-09 11:35 UTC, rekpero commented on pages/billing/_meta.json
> +  "invoices": "Invoices & Usages",
can you add the payment history in the billing section as well, you can find it in the app

2024-01-10 03:56 UTC, anataliocs commented on pages/billing/compute/topup-compute-funds.mdx
> +- Add a [Web3 Payment Method](/billing/payment-method/#connect-wallet) and deposit funds in your [Spheron escrow wallet](/billing/funds/)
Ahhh thank you this is a great call out.  Will more explicitly define those two paths.

2024-01-10 06:29 UTC, anataliocs commented on pages/billing/_meta.json
> +  "invoices": "Invoices & Usages",
Will handle in new PR:  [Add-Payment-History-page-for-Compute-Storage](https://www.notion.so/sphn/Add-Payment-History-page-for-Compute-Storage-b172d3ccca3649d39d850f5d40fdeded?pvs=4)

2024-01-10 07:01 UTC, anataliocs commented
Need to add: 

Mitra:
> can you update the main page to include storage and compute billing? like a quick intro and then 2 blocks like we have for upgrade to pro to send them to compute and storage section

2024-01-10 09:06 UTC, anataliocs commented
Compute and storage sections on root billing page added:

![image](https://github.com/spheronFdn/docs/assets/4750426/7328d726-33a4-4129-a0cc-36633bcd8741)

2024-01-10 09:46 UTC, anataliocs commented
Added Storage and compute topup elements and added to billing root page:
![image](https://github.com/spheronFdn/docs/assets/4750426/3b58c72f-cc79-4506-831d-44e06d647bac)

2024-01-11 09:21 UTC, anataliocs commented
Added Metamask SVG

![image](https://github.com/spheronFdn/docs/assets/4750426/71100bcc-ab1d-4fe8-bd21-cec5fee3d360)

2024-01-11 10:36 UTC, rekpero requested changes
last bit of changes needed and we are good to go @anataliocs really great job

2024-01-11 10:36 UTC, rekpero commented on pages/billing.mdx
> +## Top Up Compute Balance
put this above upgrade to Pro, since it is for site billing, move to below storage section

2024-01-11 10:36 UTC, rekpero commented on components/storage-guide.tsx
> +        path: "/billing/storage/storage-plan/",
Add available storage plan in the list to make it consistent even tho it's not needed but it's a part of the storage billing so it make sense to have this

2024-01-11 10:48 UTC, anataliocs commented on pages/billing.mdx
> +## Top Up Compute Balance
Definitely, that makes sense!

2024-01-11 11:05 UTC, anataliocs commented on components/storage-guide.tsx
> +        path: "/billing/storage/storage-plan/",
Yea, it looks better when it's symmetrical and it makes sense to have easy access to the page in this context

2024-01-11 11:06 UTC, anataliocs commented on pages/billing.mdx
> +## Top Up Compute Balance
Is this the layout we want?
![image](https://github.com/spheronFdn/docs/assets/4750426/dda60101-3453-419d-8b80-5b0bf2fabd0e)

2024-01-11 11:07 UTC, anataliocs commented
Also tested mobile responsive view locally:

![image](https://github.com/spheronFdn/docs/assets/4750426/a9a90eee-cdb2-4c72-aea5-aef78c3e217b)

2024-01-11 11:22 UTC, rekpero commented on pages/billing.mdx
> +## Top Up Compute Balance
yes, this is good

2024-01-11 11:27 UTC, rekpero approved these changes

2024-01-11 11:28 UTC, merged