Update favicon icon
spheronFdn/docs pull request #19
Opened 2023-04-17 17:00 UTC by Kanika1799

2023-04-17 21:17 UTC, abhinav-spheron commented on .DS_Store
Remove this file

2023-04-17 21:17 UTC, abhinav-spheron requested changes
Please check comment

2023-04-17 22:52 UTC, Kanika1799 commented on .DS_Store
Done!

2023-04-18 10:40 UTC, nitinshr135 approved these changes

2023-04-18 19:38 UTC, abhinav-spheron approved these changes

2023-04-18 19:39 UTC, merged