Add browser SDK
spheronFdn/docs pull request #22
Opened 2023-04-24 08:19 UTC by aayushmahapatra

2023-04-25 12:22 UTC, shomix reviewed
A couple of suggestions.
I would also remove the Available Methods section, and move the Upload part to the client section.

Do check with @rekpero first before making changes

2023-04-25 12:22 UTC, shomix commented on pages/sdk/browser.mdx
> +1. An express server that will be used by the frontend to get the `uploadToken` for uploading the data.
It doesn't need to be an express server.

Lets just put `An web server`

2023-04-25 12:22 UTC, shomix commented on pages/sdk/browser.mdx
> +      - The upload token for the upload.
```suggestion
      - The upload token which was fetched from your Backend server.
```

2023-04-25 12:22 UTC, shomix commented on pages/sdk/browser.mdx
> +You have to set up an express server with the `/initiate-upload` endpoint.
```suggestion
You have to set up an web server with and endpoint that will be used by your Web App to fetch the token that will be used to upload. In the example we have created a `/initiate-upload` endpoint.
```

2023-04-25 12:22 UTC, shomix commented on pages/sdk/browser.mdx
> +You have to get the `uploadToken` from the server by making a request to the `/initiate-upload` endpoint.
```suggestion
To get the `token` that is used to upload data from Browser, you will first need to send a request to your Backend to create the `token`. In our example we are going to send a request to the `/initiate-upload` endpoint.
```

2023-04-26 04:15 UTC, rekpero requested changes
check my comment

2023-04-26 04:15 UTC, rekpero commented on pages/sdk/browser.mdx
> +  token: res.uploadToken,
This should be a token extracted in the line 111
```
const token = resJson.uploadToken;
```
Just do this instead of using res, which is not present. If someone copies this code, it will not work. Please check the code example multiple times, as this is one of the most imp parts of the doc. Wrong code will give a very bad experience to the devs as they completely trust the code given in the docs.
```suggestion
  token,
```

2023-04-26 05:33 UTC, rekpero requested changes
check my comments too

2023-04-26 05:33 UTC, rekpero commented on pages/sdk/browser.mdx
> +> You can checkout the working example [here](https://github.com/spheronFdn/sdk/tree/main/examples/browser-upload).
put this at the starting at the end of the usage section - https://github.com/spheronFdn/docs/pull/22/files#diff-d629206430e48bc9c6975ee35ebf00f29a50750b1c941c4746e50d95a01347c5R33

2023-04-26 15:36 UTC, rekpero requested changes
last small change required and it's good to go now

2023-04-26 15:36 UTC, rekpero commented on pages/sdk/browser.mdx
> +const response = await fetch(`<BACKEND_URL>/initiate-upload`); // get the access token from server
```suggestion
const response = await fetch(`<BACKEND_URL>/initiate-upload`); // get the temporary access token from server
```

2023-04-26 15:55 UTC, shomix approved these changes

2023-04-26 15:55 UTC, shomix commented on pages/sdk/browser.mdx
> +}
```suggestion
{
  uploadId: string;
  bucketId: string;
  protocolLink: string;
  dynamicLinks: string[];
}
```

2023-04-26 17:49 UTC, rekpero approved these changes

2023-04-26 17:50 UTC, merged