Add site sdk docs
spheronFdn/docs pull request #23
Opened 2023-04-26 12:55 UTC by shomix

completes https://linear.app/spheron/issue/SPH-1836/add-site-sdk-docs

2023-04-28 13:46 UTC, shomix commented on components/sdk.tsx
> +    emoji: "🌐",
@rekpero what icon should be here?

2023-04-28 15:12 UTC, aayushmahapatra requested changes

2023-04-28 15:12 UTC, aayushmahapatra commented on pages.config.ts
> +  ["Site SDK", "/sdk/site"],
Add this below Browser Upload SDK.

2023-04-28 15:12 UTC, aayushmahapatra commented on components/sdk.tsx
> +    emoji: "🌐",
🚧

2023-05-12 13:53 UTC, aayushmahapatra requested changes

2023-05-12 13:53 UTC, aayushmahapatra commented on pages/sdk/site.mdx
> +<Navigation name="Spheron Site SDK" />
```suggestion
<Navigation name="Site SDK" />
```

It should be the same as in the `pages.config.ts` file.

2023-05-12 14:30 UTC, shomix commented on pages.config.ts
> +  ["Site SDK", "/sdk/site"],
Done

2023-05-12 14:30 UTC, shomix commented on pages/sdk/site.mdx
> +<Navigation name="Spheron Site SDK" />
Updated

2023-05-12 14:31 UTC, aayushmahapatra reviewed
lgtm

2023-05-17 13:29 UTC, rekpero requested changes
RC for you @shomix

2023-05-17 13:29 UTC, rekpero commented on pages/sdk/site.mdx
> +````js
this is messed up, please check

2023-05-17 13:29 UTC, rekpero commented on pages/sdk/site.mdx
> +  gitUrl, // the url of the repository
As per our last discussion, can we deploy public repo without any comments or anything like that which needs tokens? Also, add an option to disable the comments, checks or other git things

2023-05-23 04:04 UTC, rekpero requested changes
some more updates required @shomix

2023-05-23 09:34 UTC, shomix commented on pages/sdk/site.mdx
> +    MAINTAINED = "MAINTAINED",
Updated all enums

2023-05-23 09:34 UTC, shomix commented on pages/sdk/site.mdx
> +The Site SDK is a npm package, that provides support for working with Spheron Web-App organizations.
Updated

2023-05-23 09:34 UTC, shomix commented on pages/sdk/site.mdx
> +  - `skip`: number of projects to skip.
Updated across all parameters

2023-05-23 09:34 UTC, shomix commented on pages/sdk/site.mdx
> +  configuration: Configuration; // the default configuration of a project. This configuration is used for webhook deployments.
Done

2023-05-23 09:34 UTC, shomix commented on pages/sdk/site.mdx
> +````js
Fixed.

2023-05-23 09:35 UTC, shomix commented on pages/sdk/site.mdx
> +    passwordProtection?: number,; // 1 - if organization has support for password protection, otherwise 0.
Fixed it.

It is optional on our api side because the same endpoint returns for both compute and web-app organizaiton, but because here its alwasys for web-app they will always exist

2023-05-23 09:39 UTC, shomix commented on pages/sdk/site.mdx
> +  gitUrl, // the url of the repository
Nope. Only repositories for which the Git Provider Spheron App has the access will be able to be deployed ( there is a mention of it here https://docs.github.com/en/rest/deployments/deployments?apiVersion=2022-11-28 ).



Added the preferences for PR comments, commit comments, build statuses and github deployments

2023-05-23 10:29 UTC, shomix commented on pages/sdk/site.mdx
> +  - `skip: number` - the number of projects to skip.
updated to be the same as in compute

2023-05-23 10:29 UTC, shomix commented on pages/sdk/site.mdx
> +    BITBUCKET = "GITLAB"
missed it. Removed.

2023-05-24 06:52 UTC, rekpero approved these changes

2023-05-24 15:15 UTC, aayushmahapatra approved these changes
lgtm

2023-05-29 15:18 UTC, ilij4 approved these changes

2023-05-30 06:58 UTC, dusanstanis approved these changes

2023-05-30 11:16 UTC, shomix commented
Updated the order

2023-05-30 11:20 UTC, rekpero approved these changes
lgtm now

2023-05-30 11:41 UTC, merged