Add compute docs (WIP)
spheronFdn/docs pull request #24
Opened 2023-04-28 12:58 UTC by aayushmahapatra

2023-05-05 07:54 UTC, rekpero requested changes
@aayushmahapatra please check my comments and address them with priority

2023-05-05 07:54 UTC, rekpero commented on pages/compute/instance/domain.mdx
> +By default, Spheron provides a subdomain when a cluster is deployed.
Mention that domain/subdomain can only be attached to a single instance and if you want to add the same domain/subdomain to some other instance, you need to remove the domain from the existing instance

2023-05-05 07:54 UTC, rekpero commented on pages/compute/instance/domain.mdx
> +By default, Spheron provides a subdomain when a cluster is deployed.
Also we don't provide any subdomain for compute, remove this line

2023-05-05 07:54 UTC, rekpero commented on pages/compute/usage.mdx
> +<Navigation name="Usage" />
the name should be compute usage since there is a usage for site as well

2023-05-06 05:55 UTC, rekpero requested changes
just some small changes and it's good to merge now

2023-05-06 05:55 UTC, rekpero commented on pages/compute/cluster.mdx
> +To learn how to upload your docker image to docker hub, [click here](https://docs.docker.com/get-started/04_sharing_app/). \
Make it as a note

2023-05-06 05:55 UTC, rekpero commented on pages/compute/cluster.mdx
> +Spheron allows you to add environment variables while configuring your deployment.
Add a note that `when you enable secret, it will not be saved in the database.`

2023-05-06 05:55 UTC, rekpero commented on pages/compute/cluster.mdx
> +- us-east
Add `any` as well, which can deploy the container in any region. Add a note of it

2023-05-06 05:55 UTC, rekpero commented on pages/compute/cluster.mdx
> +Region refers to specific geographic locations where where a cloud service provider (CSP) has its data centers and computing resources.
don't need to write it 2 time, just reference to the 1st section

2023-05-06 08:41 UTC, rekpero requested changes
@aayushmahapatra last change man

2023-05-06 08:41 UTC, rekpero commented on pages/compute/cluster.mdx
> +  2\. Learn how to upload your docker image to docker hub [here](https://docs.docker.com/get-started/04_sharing_app/).
```suggestion
  2\. Learn how to dockerize your server and push the docker image to the docker hub [here](https://docs.docker.com/get-started/02_our_app/).
```

2023-05-06 09:43 UTC, dusanstanis approved these changes

2023-05-07 08:41 UTC, rekpero approved these changes

2023-05-07 14:53 UTC, merged