Update usage with limits interface for the Storage SDK
spheronFdn/docs pull request #25
Opened 2023-05-11 20:00 UTC by shomix

2023-05-12 05:47 UTC, rekpero requested changes
I think we should remove these from the storage side. It is not relevant to the storage side at all

2023-05-12 05:47 UTC, rekpero commented on pages/sdk/storage.mdx
> +  buildExecutionLimit?: number; // the build execution limit for the current subscription
this is not needed for storage, let's churn this up

2023-05-12 05:47 UTC, rekpero commented on pages/sdk/storage.mdx
> +  concurrentBuildLimit?: number; // how many concurrent builds can the organization have with the current subscription plan
this is not needed for storage, we have parallel uploads. remove this

2023-05-12 05:47 UTC, rekpero commented on pages/sdk/storage.mdx
> +  deploymentsPerDayLimit?: number; // the limit of how many deployments can an organization have per day
not needed, remove

2023-05-12 05:47 UTC, rekpero commented on pages/sdk/storage.mdx
> +  environmentsLimit?: number; // the limit on how many deployment environment can an organization have
remove this

2023-05-12 05:47 UTC, rekpero commented on pages/sdk/storage.mdx
> +  usedPasswordProtections?: number; // 1 - if organization has support for password protection, otherwise 0.
remove these too

2023-05-12 08:20 UTC, shomix commented on pages/sdk/storage.mdx
> +  buildExecutionLimit?: number; // the build execution limit for the current subscription
Removed it.

2023-05-12 08:21 UTC, shomix commented on pages/sdk/storage.mdx
> +  concurrentBuildLimit?: number; // how many concurrent builds can the organization have with the current subscription plan
Removed it.

2023-05-12 08:21 UTC, shomix commented on pages/sdk/storage.mdx
> +  deploymentsPerDayLimit?: number; // the limit of how many deployments can an organization have per day
Removed it.

2023-05-12 08:21 UTC, shomix commented on pages/sdk/storage.mdx
> +  environmentsLimit?: number; // the limit on how many deployment environment can an organization have
Removed.

2023-05-12 08:48 UTC, rekpero requested changes

2023-05-12 08:48 UTC, rekpero commented on pages/sdk/storage.mdx
>  interface UsageWithLimits {
Can we maybe format this interface like this maybe - 
```
{
 used: {
  bandwidth: number,
  storageArweave: number,
 },
 limit: {
  bandwidth: number,
  storageArweave: number,
 }
}
```
It will look more better this way, wdyt?

2023-05-12 10:38 UTC, shomix commented on pages/sdk/storage.mdx
>  interface UsageWithLimits {
Yep. updated the interface to match this structure. Will use it on the site sdk also.

2023-05-12 10:42 UTC, rekpero reviewed
lgtm!

2023-05-12 10:43 UTC, rekpero approved these changes
lgtm

2023-05-18 07:25 UTC, rekpero approved these changes

2023-05-18 08:14 UTC, merged