Compute docs
spheronFdn/docs pull request #27
Opened 2023-05-12 16:39 UTC by ilij4

2023-05-17 11:20 UTC, rekpero requested changes
some imp review comments for you @ilij4

2023-05-17 11:20 UTC, rekpero commented on pages/sdk/compute.mdx
> +### getDomains
Update all the project mention in the domains section with cluster

2023-05-17 11:20 UTC, rekpero commented on pages/sdk/compute.mdx
> +  variables: MarketplaceAppVariable[]; //list of enironemt variables
don't need to show this to the user

2023-05-17 11:20 UTC, rekpero commented on pages/sdk/compute.mdx
> +  searchString: "2Gi"
call it `search` only, no need to add string at the end

2023-05-17 15:41 UTC, rekpero requested changes
check this comment as well

2023-05-17 15:41 UTC, rekpero commented on pages/sdk/compute.mdx
> +const deploymentResponse: { deployment: InstanceDeployment; liveLogs: string[] } =
Let's not get the liveLogs here. do the same thing as site deployment. Just show the deployment only. 
Also create a separate method to get `getDeploymentLogs()`, `getInstanceLogs()`, `getInstanceEvents()` and remove all the logs in the `InstanceDeployment` interface

2023-05-19 16:51 UTC, shomix commented on pages/sdk/compute.mdx
> +    domains?: number; //the number of domains and subdomains an organization has
Its not optional, it will always exist.

They are optional on our API side, because we use the same endpoint for both Compute and Web-App organization. So depenedning on the organization some will exists and some will not exists.
Here we can know that compute organizations will have this properties.

2023-05-19 17:10 UTC, shomix commented on pages/sdk/compute.mdx
> +  - `path`:  (string) -health check path
```suggestion
  - `path`:  (string) - health check path
```

2023-05-22 09:43 UTC, ilij4 commented on pages/sdk/compute.mdx
> +  - `scale`: (number) - number of instances that should be created.
yap, will remove this and set it to 1 in request by default

2023-05-22 11:36 UTC, rekpero approved these changes
lgtm

2023-05-22 12:52 UTC, aayushmahapatra commented on components/sdk.tsx
> +    emoji: "🌐",
📼

2023-05-22 12:55 UTC, aayushmahapatra approved these changes
Just add this emoji 📼, everything else looks good to me.

2023-05-22 14:58 UTC, rekpero requested changes
just 1 last thing is remaining

2023-05-22 15:12 UTC, aayushmahapatra requested changes
Few changes required.

2023-05-22 15:12 UTC, aayushmahapatra commented on pages/sdk/compute.mdx
> +Follow the instructions in the [DOCS](https:// docs.spheron.network/rest-api/#creating-an-access-token) to generate this token. When you are creating the tokens, please choose **Compute** type in
```suggestion
Follow the instructions in the [DOCS](https://docs.spheron.network/rest-api/#creating-an-access-token) to generate this token. When you are creating the tokens, please choose **Compute** type in
```

2023-05-22 15:12 UTC, aayushmahapatra commented on pages/sdk/compute.mdx
> +---
Remove this.

2023-05-22 15:12 UTC, aayushmahapatra commented on pages/sdk/compute.mdx
> +Returns an list of for instance deployment logs.
```suggestion
Returns an list of for instance deployment logs
```

2023-05-22 15:12 UTC, aayushmahapatra commented on pages/sdk/compute.mdx
> +---
Remove this.

2023-05-22 15:12 UTC, aayushmahapatra commented on pages/sdk/compute.mdx
> +---
Remove this.

2023-05-22 15:15 UTC, aayushmahapatra commented on pages/sdk/compute.mdx
> +Returns list of available regions.
```suggestion
Returns list of available regions.

<Navigation name="Compute SDK" />
```

2023-05-22 15:15 UTC, aayushmahapatra commented on pages/sdk/compute.mdx
> +Returns list of available regions.
Also, import Navigation at the top.

2023-05-22 15:19 UTC, ilij4 commented on pages/sdk/compute.mdx
> +Returns an list of for instance deployment logs.
@aayushmahapatra remove '.' everywhere?

2023-05-22 16:25 UTC, aayushmahapatra commented on pages/sdk/compute.mdx
> +Returns an list of for instance deployment logs.
Nope. Only from headings.

2023-05-22 17:02 UTC, ilij4 commented on pages/sdk/compute.mdx
> +Returns an list of for instance deployment logs.
@aayushmahapatra but all the others have dots, even in other SDK docs 🤔

2023-05-22 17:39 UTC, aayushmahapatra commented on pages/sdk/compute.mdx
> +Returns an list of for instance deployment logs.
I can't see 'em. Can you send me a ss on discord? 🤔

2023-05-22 17:40 UTC, aayushmahapatra commented on pages/sdk/compute.mdx
> +Returns an list of for instance deployment logs.
Oh wait...its an error.

2023-05-22 17:41 UTC, rekpero approved these changes

2023-05-22 17:44 UTC, aayushmahapatra commented on pages/sdk/compute.mdx
> +Returns an list of for instance deployment logs.
Due to some reason this line was showing as heading. Looks good now.

2023-05-22 17:45 UTC, aayushmahapatra approved these changes

2023-05-23 08:50 UTC, dusanstanis approved these changes

2023-05-23 10:01 UTC, rekpero requested changes
@shomix @aayushmahapatra @ilij4 please check my comment

2023-05-23 10:01 UTC, rekpero commented on components/sdk.tsx
> +    body: "For Node.js based environments",
Change this to something relevant, it's the same as Storage SDK desc

2023-05-23 10:01 UTC, rekpero commented on components/sdk.tsx
> +    body: "For Node.js based environments",
@shomix @aayushmahapatra please suggest something here

2023-05-23 10:06 UTC, ilij4 commented on components/sdk.tsx
> +    body: "For Node.js based environments",
@rekpero @aayushmahapatra @shomix suggestion:
Designed to streamline work with your compute organisations.

2023-05-23 12:29 UTC, Man-Jain commented on pages/sdk/compute.mdx
> +  - \{ containerPort: 3000, exposedPort: 3000 \} - port 3000 will be mapped to randpom port.
Spelling mistake randpom

2023-05-23 14:28 UTC, aayushmahapatra approved these changes

2023-05-25 14:57 UTC, merged