Add IPFS Gateway docs
spheronFdn/docs pull request #32
Opened 2023-05-18 18:50 UTC by aayushmahapatra

2023-05-19 13:43 UTC, rekpero requested changes
lgtm, just update the benefit

2023-05-19 13:43 UTC, rekpero commented on pages/gateways.mdx
> +- **Increased Rate Limits:** With Dedicated Gateways, you can enjoy higher rate limits, allowing for more efficient content delivery and reduced bottlenecks.
add this as well - 
1. Whitelabling gateway - And add some basic content from the blog that we wrote
2. Serve your content from any IPFS node - No need to upload on spheron. You can upload on any platform and still serve them from the dedicated gateway.

2023-05-20 05:42 UTC, aayushmahapatra commented on pages/gateways.mdx
> +- **Increased Rate Limits:** With Dedicated Gateways, you can enjoy higher rate limits, allowing for more efficient content delivery and reduced bottlenecks.
Done.

2023-05-20 07:52 UTC, rekpero approved these changes

2023-05-20 07:52 UTC, merged