Add guide for pinning CID and getting pin status
spheronFdn/docs pull request #34
Opened 2023-05-25 14:42 UTC by L-tech

2023-05-26 09:00 UTC, rekpero requested changes
check my comments @L-tech

2023-05-26 09:00 UTC, rekpero commented on pages/sdk/storage.mdx
> +  pinStatus: string;
I think we should mention all the details that are sent from the IPFS node

2023-05-30 07:43 UTC, rekpero approved these changes

2023-05-31 07:44 UTC, aayushmahapatra approved these changes
lgtm

2023-06-05 08:20 UTC, merged