Add github action docs
spheronFdn/docs pull request #35
Opened 2023-05-26 14:12 UTC by shomix

completes SPH-2051

2023-05-27 10:45 UTC, aayushmahapatra requested changes

2023-05-27 10:45 UTC, aayushmahapatra commented on pages/github-action.mdx
> +## Github Action for updating Cluster Instances
```suggestion
# Github Action for updating Cluster Instances
```

2023-05-27 10:45 UTC, aayushmahapatra commented on pages/github-action.mdx
> +## Instance Update Action
What is this heading for?
It's the same as the title I guess 🤔

2023-05-27 13:10 UTC, rekpero requested changes
check my comment @shomix cc @aayushmahapatra

2023-05-27 17:17 UTC, aayushmahapatra commented on components/quick-start.tsx
> +    body: "Update Cluster Instances from github workflows.",
In that case, we can also rename `Github Action` -> `Github Actions`

2023-05-29 11:45 UTC, shomix commented on pages/github-action.mdx
> +## Instance Update Action
Yep, updated the title.

2023-05-29 11:46 UTC, shomix commented on components/quick-start.tsx
> +    body: "Update Cluster Instances from github workflows.",
Extracted a separate section for github actions

2023-05-29 11:51 UTC, aayushmahapatra approved these changes
lgtm

2023-05-29 12:06 UTC, rekpero requested changes
Need some small text changes, @shomix please check

2023-05-29 12:06 UTC, rekpero commented on components/github-actions.tsx
> +    title: "Instance Update Action",
```suggestion
    title: "Instance Update",
```

2023-05-29 12:06 UTC, rekpero commented on pages/github-actions/instance-update-action.mdx
> +- **env( optional )**: The environment variables that should be used. The environment variables need to be provided each time the instance is updated. You will be able to see the value of the environ
add a for eg. and mention how it should look like in the config

2023-05-29 12:06 UTC, rekpero commented on pages/github-actions/instance-update-action.mdx
> +- **secret-env( optional )**: The secret environment variables that should be used. The secret environment variables need to be provided each time the instance is updated. You will not be able to see
same here

2023-05-29 12:06 UTC, rekpero commented on pages/github-actions/instance-update-action.mdx
> +- **instance-id**: The ID of the instance that should be updated.
Add this, You need to create the instance in the dashboard first and then pass the id from the instance dashboard

2023-05-29 12:06 UTC, rekpero commented on pages/github-actions/instance-update-action.mdx
> +- **order-id**: The Order ID of the updated instance.
change it to `deployment-id`: The deployment ID of the updated instance

2023-05-29 12:25 UTC, shomix commented on components/github-actions.tsx
> +    title: "Instance Update Action",
Do you mean just here, on the github-actions page, or everywhere?

ATM, I have just updated here.

2023-05-29 12:25 UTC, shomix commented on pages/github-actions/instance-update-action.mdx
> +- **env( optional )**: The environment variables that should be used. The environment variables need to be provided each time the instance is updated. You will be able to see the value of the environ
Added a link that is pointing to the usage example. Is that ok?

2023-05-29 12:25 UTC, shomix commented on pages/github-actions/instance-update-action.mdx
> +- **secret-env( optional )**: The secret environment variables that should be used. The secret environment variables need to be provided each time the instance is updated. You will not be able to see
Added a link that is pointing to the usage example. Is that ok?

2023-05-29 12:25 UTC, shomix commented on pages/github-actions/instance-update-action.mdx
> +- **instance-id**: The ID of the instance that should be updated.
Added

2023-05-29 12:26 UTC, shomix commented on pages/github-actions/instance-update-action.mdx
> +- **order-id**: The Order ID of the updated instance.
Updated here, and in the github action https://github.com/spheronFdn/instance-update-action/pull/6

2023-05-29 13:03 UTC, rekpero commented on components/github-actions.tsx
> +    title: "Instance Update Action",
just here

2023-05-29 13:05 UTC, rekpero commented on pages/github-actions/instance-update-action.mdx
> +- **secret-env( optional )**: The secret environment variables that should be used. The secret environment variables need to be provided each time the instance is updated. You will not be able to see
I was thinking of just `'[ "key1=value1", "key2=value2" ]'` in here rather than the whole yml just for better visibility

2023-05-29 13:13 UTC, shomix commented on pages/github-actions/instance-update-action.mdx
> +- **secret-env( optional )**: The secret environment variables that should be used. The secret environment variables need to be provided each time the instance is updated. You will not be able to see
Updated

2023-05-29 13:13 UTC, shomix commented on pages/github-actions/instance-update-action.mdx
> +- **env( optional )**: The environment variables that should be used. The environment variables need to be provided each time the instance is updated. You will be able to see the value of the environ
Updated

2023-05-29 13:29 UTC, rekpero approved these changes
lgtm now

2023-05-29 15:05 UTC, merged