Add public gateway docs
spheronFdn/docs pull request #42
Opened 2023-06-13 15:57 UTC by shomix

This PR will:
- Add a page to the docs for the Spheron Public Gateway

2023-06-14 10:54 UTC, aayushmahapatra requested changes
In quick start, update the route for `Gateways` and link it to `Dedicated gateways`.

2023-06-14 10:54 UTC, aayushmahapatra commented on pages/gateways/_meta.json
> +  "spheron-gateway": "Spheron Gateway"
Can we name it something like Public Gateway?
Cause even the dedicated gateway is a Spheron Gateway. 🤔

2023-06-19 09:23 UTC, shomix commented on pages/gateways/_meta.json
> +  "spheron-gateway": "Spheron Gateway"
renamed to `Public Gateway`

2023-06-19 09:23 UTC, shomix commented
> In quick start, update the route for `Gateways` and link it to `Dedicated gateways`.

done.

2023-06-19 14:57 UTC, rekpero requested changes
Small RC

2023-06-19 15:17 UTC, rekpero approved these changes

2023-06-19 15:29 UTC, merged