Compute SDK - storage update
spheronFdn/docs pull request #50
Opened 2023-06-28 14:14 UTC by ilij4

2023-06-29 16:48 UTC, rekpero requested changes
some comment from my side

2023-06-29 16:48 UTC, rekpero commented on pages/sdk/compute.mdx
> +    // machineImageId: ventusSmallId
should this be commented? is it optional?

2023-06-29 16:48 UTC, rekpero commented on pages/sdk/compute.mdx
> +- `machineImageId` (string) - name of machine image which should be used for deploying instance. List of available can be aquierd from [get section under compute machine section](/sdk/compute/#get-4)
why not just make it optional? then check if any of this or custom spec is provided in the param and throw error if both are not mentioned

2023-06-29 16:48 UTC, rekpero commented on pages/sdk/compute.mdx
> +- `machineImageId` (string) - name of machine image which should be used for deploying instance. List of available can be aquierd from [get section under compute machine section](/sdk/compute/#get-4)
do the same with instance

2023-06-30 06:56 UTC, ilij4 commented on pages/sdk/compute.mdx
> +    // machineImageId: ventusSmallId
it is, I've just put it there so user can see how it should be done. I can remove it tho, if u think its not needed

2023-06-30 07:02 UTC, ilij4 commented on pages/sdk/compute.mdx
> +- `machineImageId` (string) - name of machine image which should be used for deploying instance. List of available can be aquierd from [get section under compute machine section](/sdk/compute/#get-4)
@rekpero yes, already added that check, it should throw an error in case both custom spec and machine image is specified. I just added it in docs as well, to make it more clear for user
I'll put note that it is optional

2023-06-30 10:25 UTC, rekpero commented on pages/sdk/compute.mdx
> +    // machineImageId: ventusSmallId
no its fine then

2023-06-30 10:29 UTC, rekpero reviewed
1 small comment. can be ignored as well

2023-06-30 10:29 UTC, rekpero commented on pages/sdk/compute.mdx
> +  - `args` (string[]) - list of params for docker CMD command.
shall we make these 2 optional as well?

2023-07-04 09:12 UTC, 97ilija97 commented on pages/sdk/compute.mdx
> +      //machineImageId: machineId;
@shomix its meant to be an indication that both custom specs and machineImageId are valid options

2023-07-04 09:15 UTC, ilij4 commented on pages/sdk/compute.mdx
> +      //machineImageId: machineId;
@shomix its optional and meant to be an indication that both machineImageId and customSpecs are valid options

2023-07-04 09:22 UTC, shomix approved these changes

2023-07-05 09:33 UTC, rekpero requested changes
just a small issue was found and a suggestion. please check @ilij4

2023-07-05 09:33 UTC, rekpero commented on pages/sdk/compute.mdx
> +- `args`  (string[]) - list of params for docker CMD command.
are these not optional?

2023-07-05 09:33 UTC, rekpero commented on pages/sdk/compute.mdx
> +- `doamin`
this should be domain
```suggestion
- `domain`
```

2023-07-05 09:45 UTC, aayushmahapatra approved these changes
Lgtm

2023-07-05 10:32 UTC, rekpero approved these changes

2023-07-05 10:32 UTC, merged