Add Compute Scaling
spheronFdn/docs pull request #66
Opened 2023-08-14 16:20 UTC by aayushmahapatra

2023-08-21 10:00 UTC, rekpero approved these changes

2023-08-21 10:01 UTC, rekpero requested changes
check my comment

2023-08-21 10:01 UTC, rekpero commented on pages/compute/scaling.mdx
> +1. No Scaling
make these grid boxes @aayushmahapatra wdyt?

2023-08-21 10:02 UTC, aayushmahapatra commented on pages/compute/scaling.mdx
> +1. No Scaling
Lemme check

2023-08-22 06:16 UTC, rekpero approved these changes

2023-08-22 06:17 UTC, rekpero requested changes

2023-08-22 06:17 UTC, rekpero commented on components/scaling.tsx
> +    emoji: "🔴",
use the emoji that is present on the platform. they have some emoji beside the name

2023-08-22 14:26 UTC, rekpero approved these changes

2023-08-22 14:26 UTC, merged