Add docs for storage version two
spheronFdn/docs pull request #70
Opened 2023-08-17 13:37 UTC by shomix

- needs improvments

2023-09-04 08:47 UTC, rekpero requested changes

2023-09-04 08:47 UTC, rekpero commented on pages/sdk/storage-v2.mdx
> +const { numberOfBuckets, numberOfUploads } =
mention how to intialise the spheron client here as well. Also I'm confused how to safeguard the web app from where the data will be migrated since we are not taking it's token anywhere as per this doc, then anyone can migrate from any webapp if they know it's id

2023-09-04 08:47 UTC, rekpero commented on pages/sdk/storage-v2.mdx
> +### Bucket Ipns Records
```suggestion
### IPNS Records
```

2023-09-04 08:47 UTC, rekpero commented on pages/sdk/storage-v2.mdx
> +#### Get Bucket Ipns records
```suggestion
#### Get Bucket IPNS records
```
do this everywhere

2023-09-04 08:47 UTC, rekpero commented on pages/sdk/storage-v2.mdx
> +### Upload
put upload first, then org usage, ipns, bucket. update it in this order

2023-09-04 08:47 UTC, rekpero commented on pages/sdk/storage-v2.mdx
> +````
there is something wrong here with syntax, please check

2023-09-04 08:47 UTC, rekpero commented on pages/sdk/storage-v2.mdx
> +Used to migrate the Buckets and their Uploads from Web App organization to Storage organization.
not web app, make it Static Site

2023-09-04 08:47 UTC, rekpero commented on pages/sdk/storage-v2.mdx
> +Executing the migration will move the following data from webapp to storage organization:
```suggestion
Executing the migration will move the following data from static site to storage organization:
```

2023-09-04 08:47 UTC, rekpero commented on pages/sdk/storage-v2.mdx
> +getBucket, getBucketUploadCount, getBucketUploads, getOrganizationUsage, getUpload, all the ipns ones
mention the ipns methods as well rather than mention like this and mention it in bullet list format

2023-09-04 09:55 UTC, shomix commented on pages/sdk/storage-v2.mdx
> +const { numberOfBuckets, numberOfUploads } =
There is a restriction on the BE. The user needs to be an owner on both the storage and web-app organization.

2023-09-04 14:44 UTC, aayushmahapatra requested changes
Few changes required

2023-09-04 15:27 UTC, shomix commented on pages/sdk/storage-v2.mdx
> +const { numberOfBuckets, numberOfUploads } =
Also added a note that the token for storage organization should be used, and that the user needs to be an owner of both organizations.

2023-09-04 15:27 UTC, shomix commented on pages/sdk/storage-v2.mdx
> +### Bucket Ipns Records
Done

2023-09-04 15:27 UTC, shomix commented on pages/sdk/storage-v2.mdx
> +#### Get Bucket Ipns records
Done

2023-09-04 15:27 UTC, shomix commented on pages/sdk/storage-v2.mdx
> +### Upload
Done

2023-09-04 15:27 UTC, shomix commented on pages/sdk/storage-v2.mdx
> +````
Fixed

2023-09-04 15:36 UTC, shomix commented on pages/sdk/storage.mdx
> +  The `@spheron/storage` SDK `<2.0.0` require a token for a Web App organization, and all the usages are bound to the provided organization.
Done.

2023-09-04 15:37 UTC, shomix commented on pages/sdk/storage-v2.mdx
> +<Navigation name="Storage SDK V2" />
done

2023-09-04 15:37 UTC, shomix commented on pages/sdk/storage-v2.mdx
> +getBucket, getBucketUploadCount, getBucketUploads, getOrganizationUsage, getUpload, all the ipns ones
do0ne, check it out

2023-09-04 15:37 UTC, shomix commented on pages/sdk/storage-v2.mdx
> +Executing the migration will move the following data from webapp to storage organization:
done in all places

2023-09-04 15:37 UTC, shomix commented on pages/sdk/storage-v2.mdx
> +Used to migrate the Buckets and their Uploads from Web App organization to Storage organization.
done

2023-09-04 17:00 UTC, aayushmahapatra requested changes

2023-09-04 17:00 UTC, aayushmahapatra commented on pages/sdk/storage-v2.mdx
> +## Available Methods
What is this empty heading for?

2023-09-04 17:00 UTC, aayushmahapatra commented on pages/sdk/storage-v2.mdx
> +<Navigation name="Storage SDK V2" />
Remove these -> ``` around Navigation.

2023-09-04 17:19 UTC, shomix commented on pages/sdk/storage-v2.mdx
> +## Available Methods
removed,

2023-09-04 17:20 UTC, shomix commented on pages/sdk/storage-v2.mdx
> +<Navigation name="Storage SDK V2" />
fixed

2023-09-04 17:22 UTC, aayushmahapatra approved these changes

2023-09-05 05:36 UTC, aayushmahapatra requested changes

2023-09-05 05:36 UTC, aayushmahapatra commented on pages/sdk/browser.mdx
> +  - For `<2.0.0` versions, Please choose `web app` type in the dashboard while generating the Access Token.
```suggestion
  - For `<2.0.0` versions, Please choose `static site` type in the dashboard while generating the Access Token.
```

2023-09-05 08:47 UTC, aayushmahapatra approved these changes

2023-09-05 12:01 UTC, rekpero approved these changes

2023-09-05 13:59 UTC, merged