Add auto scaling docs
spheronFdn/docs pull request #79
Opened 2023-08-22 16:42 UTC by aayushmahapatra

Only description with coming soon.

2023-08-28 17:12 UTC, rekpero requested changes

2023-08-28 17:12 UTC, rekpero commented on pages/compute/scaling/no.mdx
> +# No Scaling
why is this page here? we have no-scaling page in the docs right? I think something went wrong with the merge conflict. please check @aayushmahapatra

2023-08-29 10:10 UTC, rekpero requested changes
Check my comment

2023-08-29 10:10 UTC, rekpero commented on pages/compute/scaling/manual-scaling.mdx
> +  [https://meetings.hubspot.com/prashant-maurya/scaling-demo](https://meetings.hubspot.com/prashant-maurya/scaling-demo)
```suggestion
  [link](https://meetings.hubspot.com/prashant-maurya/scaling-demo)
```

2023-08-29 10:14 UTC, aayushmahapatra commented on pages/compute/scaling/manual-scaling.mdx
> +  [https://meetings.hubspot.com/prashant-maurya/scaling-demo](https://meetings.hubspot.com/prashant-maurya/scaling-demo)
oh 😂

2023-08-29 10:28 UTC, rekpero approved these changes

2023-08-29 10:29 UTC, merged