Add migration docs from <v2 to >=v2
spheronFdn/docs pull request #99
Opened 2023-09-22 05:22 UTC by aayushmahapatra

2023-09-28 13:19 UTC, rekpero requested changes

2023-09-28 13:19 UTC, rekpero commented on pages/sdk/storage-v2.mdx
> +  Site organizations. it.
what is `it.` at the end doing?

2023-09-28 13:32 UTC, rekpero requested changes
check my comments

2023-09-28 13:32 UTC, rekpero commented on pages/storage/migration.mdx
> +# Migration from &lt;2.0.0 to >=2.0.0
name the sidebar title `SDK Migration`

2023-09-28 13:32 UTC, rekpero commented on pages/storage/migration.mdx
> +# Migration from &lt;2.0.0 to >=2.0.0
Also 
```suggestion
# SDK Migration from &lt;2.0.0 to >=2.0.0
```

2023-09-28 13:32 UTC, rekpero commented on pages/storage/migration.mdx
> +- Starting from version 2.0.0, the SDK now requires a token for a **Storage** organization. All SDK usages are bound to this Storage organization.
mention how to create token for current SDK

2023-09-28 13:32 UTC, rekpero commented on pages/storage/migration.mdx
> +2. Create an access token for the **Storage** organization. This token should be used when initializing the **SpheronClient**.
Add this `Learn how to create access token here`

2023-09-28 13:32 UTC, rekpero commented on pages/storage/migration.mdx
> +Version **2.0.0** of the `@spheron/storage` SDK brings significant changes and improvements.
@spheron/storage should be link to the npm package

2023-09-28 13:42 UTC, aayushmahapatra commented on pages/storage/migration.mdx
> +# Migration from &lt;2.0.0 to >=2.0.0
Done in #102

2023-09-28 14:08 UTC, aayushmahapatra commented on pages/storage/migration.mdx
> +    staticSiteOrganizationId
It's correct. Confirmed with @shomix .

2023-09-28 14:08 UTC, aayushmahapatra commented on pages/storage/migration.mdx
> +- Starting from version 2.0.0, the SDK now requires a token for a **Storage** organization. All SDK usages are bound to this Storage organization.
Done.

2023-09-29 11:31 UTC, rekpero approved these changes

2023-09-29 13:23 UTC, merged